version: "3.7"

services:
  choiceapp-db-dev:
    build: db
    env_file: db/.env
    ports:
    - 5432:5432
    volumes:
      - choiceapp-db:/var/lib/postgresql/data

  choiceapp-backend-dev:
    build: backend
    env_file: backend/.env
    depends_on:
      - choiceapp-db-dev

  choiceapp-bff-dev:
    build: bff
    command: npm start
    env_file: bff/.env
    volumes:
      - ./sftp-to-dev/data/bff:/app
    depends_on:
      - choiceapp-backend-dev

  choiceapp-frontend-dev:
    build: frontend
    command: npm run dev
    env_file: frontend/.env
    volumes:
      - ./sftp-to-dev/data/frontend:/app
    depends_on:
      - choiceapp-bff-dev

  sftp-to-dev:
    build: sftp-to-dev
    restart: always
    command: /usr/sbin/sshd -D
    volumes:
      - ./sftp-to-dev/data/frontend:/app/frontend
      - ./sftp-to-dev/data/bff:/app/bff
    ports:
      - "1181:22"

volumes:
  choiceapp-db:

networks:
  default:
    external:
      name: dev-net
