version: "3.7"

services:
  choiceapp-db:
    build: db
    image: ghcr.io/melchugin/choiceapp-db:prod
    container_name: choiceapp-db
    env_file: db/.env
    restart: always

  choiceapp-backend:
    build: backend
    image: ghcr.io/melchugin/choiceapp-backend:prod
    container_name: choiceapp-backend
    env_file: backend/.env
    restart: always
    depends_on:
      - choiceapp-db

  choiceapp-bff:
    build: bff
    image: ghcr.io/melchugin/choiceapp-bff:prod
    container_name: choiceapp-bff
    env_file: bff/.env
    restart: always
    depends_on:
      - choiceapp-db
  choiceapp-frontend:
    build: frontend
    image: ghcr.io/melchugin/choiceapp-frontend:prod
    container_name: choiceapp-frontend
    env_file: frontend/.env
    restart: always
    depends_on:
      - choiceapp-bff

networks:
  default:
    external:
      name: ingress
