version: "3.7"

services:
  choiceapp-db:
    build: db
    image: ghcr.io/melchugin/choiceapp-db:prod
    container_name: choiceapp-db
    env_file: db/.env
    ports:
      - 5432:5432
    restart: on-failure

  choiceapp-core:
    build: core
    image: ghcr.io/melchugin/choiceapp-core:prod
    container_name: choiceapp-core
    env_file: core/.env
    ports:
      - 9090:9090
    restart: on-failure
    depends_on:
      - choiceapp-db

  choiceapp-backend:
    build: backend
    image: ghcr.io/melchugin/choiceapp-backend:prod
    container_name: choiceapp-backend
    env_file: backend/.env
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - choiceapp-db
  # choiceapp-frontend:
  #   build: frontend
  #   image: ghcr.io/melchugin/choiceapp-frontend:prod
  #   container_name: choiceapp-frontend
  #   # env_file: core/.env
  #   ports:
  #     - 8080:8080
  #   restart: on-failure
  #   depends_on:
  #     - choiceapp-backend
# networks:
#   default:
#     external:
#       name: nginx_http-net
