version: "3.7"

services:
  choiceapp-db:
    build: db
    image: ghcr.io/melchugin/choiceapp-db:prod
    container_name: choiceapp-db
    env_file: db/.env
    restart: always

  choiceapp-core:
    build: core
    image: ghcr.io/melchugin/choiceapp-core:prod
    container_name: choiceapp-core
    env_file: core/.env
    restart: always
    depends_on:
      - choiceapp-db

  choiceapp-backend:
    build: backend
    image: ghcr.io/melchugin/choiceapp-backend:prod
    container_name: choiceapp-backend
    env_file: backend/.env
    restart: always
    depends_on:
      - choiceapp-db
  choiceapp-frontend:
    build: frontend
    image: ghcr.io/melchugin/choiceapp-frontend:prod
    container_name: choiceapp-frontend
    env_file: core/.env
    restart: always
    depends_on:
      - choiceapp-backend

networks:
  default:
    external:
      name: ingress
