name: Docker image stage CI

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: |
          touch {db,backend,bff,frontend}/.env.stage
          docker-compose -f docker-compose.stage.yml build --compress --force-rm --parallel --pull
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/stage'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push dev Docker images
        if: github.event_name == 'push' && github.ref == 'refs/heads/stage'
        run: |
          docker images --format "{{.Repository}}:{{.Tag}}" ghcr.io/${{ github.repository_owner }}/choiceapp-* | while read IMAGE; do
            IMAGE_ID=$(echo $IMAGE | awk -F ":" '{print $1}')
            docker tag $IMAGE $IMAGE_ID:$GITHUB_SHA
            docker push $IMAGE_ID
          done
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/stage'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare ssh key
        run: |
          echo "$DEPLOY_PRIVATE_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Deply to dev stand
        run: |
          ssh -i /tmp/deploy_key -p $DEPLOY_PORT -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git pull && docker-compose -f docker-compose.stage.yml pull && docker-compose -f docker-compose.stage.yml up --force-recreate --no-build --detach"
          rm -f /tmp/deploy_key
        env:
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_STAGE_PATH }}
